### ISSUE TITLE
Checklist for Open Source Software

### ISSUE THREAD

**Issue by pescini** [qLSLab/GPRuler#1]
## General checks

- Repository
  - [x] Software code available on a public repository
- License
  - [x] A plain-text `LICENSE` file with the contents of an OSI approved software license
- Installation
  - [x] List of dependencies
  - [ ] Provide the software via a package manager
    - [ ] Conda via [Bioconda](https://bioconda.github.io/)
    - [ ] Language specific package manager: Pypi, Bioconductor, etc
  - [x] Installation proceeding as outlined in the documentation
- Code structure
  - 
- Automated tests
  - [ ] Continuous integration with automated tests verifying the functionality of the software
- Versioning & DOI
  - [ ] Connect repository to archiving tool like [Zenodo](https://guides.github.com/activities/citable-code/)
  - [ ] Generate releases often

## Documentation

- [x] `README.md`
- [ ] Documentation together with the code: [GitHub page](https://pages.github.com/), [ReadTheDoc](https://readthedocs.org/)
- [ ] A statement of need: Section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is
- [x] Installation instructions: Clearly-stated list of dependencies, installation guideline
- [x] Example usage: Examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] Functionality documentation: Documentation of the core functionality of the software documented to a satisfactory level (e.g., API method documentation)
- [ ] Performance
- [ ] Community guidelines: Clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
  - [ ] Code of Conduct
  - [ ] `CONTRIBUTING.md` file
  - [ ] Roadmap
- [ ] API documentation inside the functions

Credits to @bebatut
